// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: client/arith_service.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int32                  `protobuf:"varint,1,opt,name=A,proto3" json:"A,omitempty"`
	B             int32                  `protobuf:"varint,2,opt,name=B,proto3" json:"B,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoArgs) Reset() {
	*x = ProtoArgs{}
	mi := &file_client_arith_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoArgs) ProtoMessage() {}

func (x *ProtoArgs) ProtoReflect() protoreflect.Message {
	mi := &file_client_arith_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoArgs.ProtoReflect.Descriptor instead.
func (*ProtoArgs) Descriptor() ([]byte, []int) {
	return file_client_arith_service_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoArgs) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *ProtoArgs) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

type ProtoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C             int32                  `protobuf:"varint,1,opt,name=C,proto3" json:"C,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoReply) Reset() {
	*x = ProtoReply{}
	mi := &file_client_arith_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoReply) ProtoMessage() {}

func (x *ProtoReply) ProtoReflect() protoreflect.Message {
	mi := &file_client_arith_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoReply.ProtoReflect.Descriptor instead.
func (*ProtoReply) Descriptor() ([]byte, []int) {
	return file_client_arith_service_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoReply) GetC() int32 {
	if x != nil {
		return x.C
	}
	return 0
}

var File_client_arith_service_proto protoreflect.FileDescriptor

const file_client_arith_service_proto_rawDesc = "" +
	"\n" +
	"\x1aclient/arith_service.proto\x12\x06client\"'\n" +
	"\tProtoArgs\x12\f\n" +
	"\x01A\x18\x01 \x01(\x05R\x01A\x12\f\n" +
	"\x01B\x18\x02 \x01(\x05R\x01B\"\x1a\n" +
	"\n" +
	"ProtoReply\x12\f\n" +
	"\x01C\x18\x01 \x01(\x05R\x01CB\x0eZ\fnrRPC/clientb\x06proto3"

var (
	file_client_arith_service_proto_rawDescOnce sync.Once
	file_client_arith_service_proto_rawDescData []byte
)

func file_client_arith_service_proto_rawDescGZIP() []byte {
	file_client_arith_service_proto_rawDescOnce.Do(func() {
		file_client_arith_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_arith_service_proto_rawDesc), len(file_client_arith_service_proto_rawDesc)))
	})
	return file_client_arith_service_proto_rawDescData
}

var file_client_arith_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_client_arith_service_proto_goTypes = []any{
	(*ProtoArgs)(nil),  // 0: client.ProtoArgs
	(*ProtoReply)(nil), // 1: client.ProtoReply
}
var file_client_arith_service_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_client_arith_service_proto_init() }
func file_client_arith_service_proto_init() {
	if File_client_arith_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_arith_service_proto_rawDesc), len(file_client_arith_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_arith_service_proto_goTypes,
		DependencyIndexes: file_client_arith_service_proto_depIdxs,
		MessageInfos:      file_client_arith_service_proto_msgTypes,
	}.Build()
	File_client_arith_service_proto = out.File
	file_client_arith_service_proto_goTypes = nil
	file_client_arith_service_proto_depIdxs = nil
}
